scratchmain : "/nfs/scistore12/hpcgrp/jyeung/IST_data/Siegert_lab/motevo_outputs"
windowsf : "/nfs/scistore12/hpcgrp/jyeung/IST_data/Siegert_lab/multiome/Multiome/cellranger_outputs/scATAC/consensus_peak_calling/consensus_regions.bed"
windowsnoext : "consensus_regions"
fastaref : "/nfs/scistore12/hpcgrp/jyeung/IST_data/public_data/genomes/fastas_2019/mm10_upper.fa"
wmdir : "/nfs/scistore12/hpcgrp/jyeung/IST_data/public_data/WMs/SwissRegulon/mm10_weight_matrices_v2_split"
sitecountscript : "/nfs/scistore12/hpcgrp/jyeung/projects/motif_inference/utils/calculate_sitecount.sbatch.py"
motevobin : "/nfs/scistore12/hpcgrp/jyeung/projects/motif_inference/software/motevo_ver1.12/source/motevo"
bedtoolsbin : "/nfs/scistore12/hpcgrp/jyeung/projects/motif_inference/software/bedtools2/bin/bedtools"
genomeprefix : "mm10"
projdir : "/nfs/scistore12/hpcgrp/jyeung/projects/motif_inference/motevo"
